version: '3.1'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 46lory
      MYSQL_DATABASE: db_example
    ports:
      - "3307:3306"
  web:
    image: httpd:latest
    ports:
      - "80:80"
    depends_on:
      - db
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db